//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_4_8_21.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_admin
    {
        public int a_id { get; set; }
        public string a_name { get; set; }
        public string a_email { get; set; }
        public string a_password { get; set; }
    }
}
