//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_4_8_21.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_order
    {
        public int o_id { get; set; }
        public string o_items { get; set; }
        public Nullable<int> u_fk { get; set; }
        public Nullable<System.DateTime> o_date { get; set; }
        public Nullable<int> o_total { get; set; }
        public string o_status { get; set; }
        public string o_payment { get; set; }
        public string o_billing_address { get; set; }
        public string o_billing_name { get; set; }
        public string quantity { get; set; }
    
        public virtual tbl_user tbl_user { get; set; }
    }
}
